[2019-12-09 19:33:57,449][MainThread:2320][C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pika\adapters\select_connection.py:427][DEBUG][Using SelectPoller]
[2019-12-09 19:33:57,450][MainThread:2320][C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pika\adapters\base_connection.py:168][DEBUG][Created default connection workflow <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x000002C5BAE044C8>]
[2019-12-09 19:33:57,450][MainThread:2320][C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pika\adapters\utils\connection_workflow.py:656][DEBUG][Starting AMQP Connection workflow asynchronously.]
[2019-12-09 19:33:57,451][MainThread:2320][C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pika\adapters\select_connection.py:263][DEBUG][call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x000002C5BAE04348> with deadline=194544.953 and callback=functools.partial(<bound method AMQPConnectionWorkflow._start_new_cycle_async of <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x000002C5BAE044C8>>, first=True); now=194544.953; delay=0]
[2019-12-09 19:33:57,451][MainThread:2320][C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pika\adapters\utils\connection_workflow.py:753][DEBUG][Beginning a new AMQP connection workflow cycle; attempts remaining after this: 0]
[2019-12-09 19:33:57,451][MainThread:2320][C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pika\adapters\select_connection.py:263][DEBUG][call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x000002C5BAE5D148> with deadline=194544.953 and callback=<bound method AMQPConnectionWorkflow._try_next_config_async of <pika.adapters.utils.connection_workflow.AMQPConnectionWorkflow object at 0x000002C5BAE044C8>>; now=194544.953; delay=0]
[2019-12-09 19:33:57,451][MainThread:2320][C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pika\adapters\utils\connection_workflow.py:779][DEBUG][_try_next_config_async: '127.0.0.1':5672]
[2019-12-09 19:33:57,452][Thread-1:28028][C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pika\adapters\select_connection.py:478][DEBUG][add_callback_threadsafe: added callback=<bound method _AddressResolver._dispatch_result of <pika.adapters.utils.selector_ioloop_adapter._AddressResolver object at 0x000002C5BAE5D2C8>>]
[2019-12-09 19:33:57,452][MainThread:2320][C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pika\adapters\select_connection.py:491][DEBUG][process_timeouts: invoking callback=<bound method _AddressResolver._dispatch_result of <pika.adapters.utils.selector_ioloop_adapter._AddressResolver object at 0x000002C5BAE5D2C8>>]
